/**
 * 朝代种子数据
 */

import type { NewDynasty } from './schema.js'

export const dynastyData: NewDynasty[] = [
  // 秦汉
  {
    id: 'qin',
    name: '秦',
    aliases: JSON.stringify(['秦朝']),
    startYear: -221,
    endYear: -206,
    era: '秦汉',
    sortOrder: 10,
  },
  {
    id: 'qin-former',
    name: '前秦',
    aliases: JSON.stringify(['苻秦', '符秦']),
    startYear: 351,
    endYear: 394,
    era: '魏晋南北朝',
    sortOrder: 55,
  },
  {
    id: 'qin-later',
    name: '后秦',
    aliases: JSON.stringify(['姚秦']),
    startYear: 384,
    endYear: 417,
    era: '魏晋南北朝',
    sortOrder: 56,
  },
  {
    id: 'han-west',
    name: '西汉',
    aliases: JSON.stringify(['前汉']),
    startYear: -202,
    endYear: 8,
    era: '秦汉',
    sortOrder: 20,
  },
  {
    id: 'han-east',
    name: '东汉',
    aliases: JSON.stringify(['后汉']),
    startYear: 25,
    endYear: 220,
    era: '秦汉',
    sortOrder: 30,
  },

  // 三国
  {
    id: 'three-kingdoms',
    name: '三国',
    aliases: null,
    startYear: 220,
    endYear: 280,
    era: '三国',
    sortOrder: 40,
  },
  {
    id: 'wei-cao',
    name: '曹魏',
    aliases: JSON.stringify(['魏']),
    startYear: 220,
    endYear: 265,
    era: '三国',
    sortOrder: 41,
  },
  {
    id: 'wu',
    name: '吴',
    aliases: JSON.stringify(['东吴', '孙吴']),
    startYear: 222,
    endYear: 280,
    era: '三国',
    sortOrder: 42,
  },
  {
    id: 'shu',
    name: '蜀',
    aliases: JSON.stringify(['蜀汉']),
    startYear: 221,
    endYear: 263,
    era: '三国',
    sortOrder: 43,
  },

  // 两晋
  {
    id: 'jin-west',
    name: '西晋',
    aliases: null,
    startYear: 265,
    endYear: 316,
    era: '魏晋南北朝',
    sortOrder: 50,
  },
  {
    id: 'jin-east',
    name: '东晋',
    aliases: null,
    startYear: 317,
    endYear: 420,
    era: '魏晋南北朝',
    sortOrder: 51,
  },

  // 南北朝 - 南朝
  {
    id: 'song-liu',
    name: '刘宋',
    aliases: JSON.stringify(['南朝宋']),
    startYear: 420,
    endYear: 479,
    era: '魏晋南北朝',
    sortOrder: 60,
  },
  {
    id: 'qi-south',
    name: '南齐',
    aliases: JSON.stringify(['齐']),
    startYear: 479,
    endYear: 502,
    era: '魏晋南北朝',
    sortOrder: 61,
  },
  {
    id: 'liang',
    name: '梁',
    aliases: JSON.stringify(['南梁']),
    startYear: 502,
    endYear: 557,
    era: '魏晋南北朝',
    sortOrder: 62,
  },
  {
    id: 'chen',
    name: '陈',
    aliases: JSON.stringify(['南陈']),
    startYear: 557,
    endYear: 589,
    era: '魏晋南北朝',
    sortOrder: 63,
  },

  // 南北朝 - 北朝
  {
    id: 'wei-north',
    name: '北魏',
    aliases: JSON.stringify(['元魏', '后魏', '拓跋魏']),
    startYear: 386,
    endYear: 534,
    era: '魏晋南北朝',
    sortOrder: 70,
  },
  {
    id: 'wei-east',
    name: '东魏',
    aliases: null,
    startYear: 534,
    endYear: 550,
    era: '魏晋南北朝',
    sortOrder: 71,
  },
  {
    id: 'wei-west',
    name: '西魏',
    aliases: null,
    startYear: 535,
    endYear: 556,
    era: '魏晋南北朝',
    sortOrder: 72,
  },
  {
    id: 'qi-north',
    name: '北齐',
    aliases: null,
    startYear: 550,
    endYear: 577,
    era: '魏晋南北朝',
    sortOrder: 73,
  },
  {
    id: 'zhou-north',
    name: '北周',
    aliases: null,
    startYear: 557,
    endYear: 581,
    era: '魏晋南北朝',
    sortOrder: 74,
  },

  // 隋唐五代
  {
    id: 'sui',
    name: '隋',
    aliases: JSON.stringify(['隋朝']),
    startYear: 581,
    endYear: 618,
    era: '隋唐五代',
    sortOrder: 80,
  },
  {
    id: 'tang',
    name: '唐',
    aliases: JSON.stringify(['唐朝']),
    startYear: 618,
    endYear: 907,
    era: '隋唐五代',
    sortOrder: 90,
  },
  {
    id: 'five-dynasties',
    name: '五代',
    aliases: JSON.stringify(['五代十国']),
    startYear: 907,
    endYear: 960,
    era: '隋唐五代',
    sortOrder: 100,
  },
  {
    id: 'liang-later',
    name: '后梁',
    aliases: null,
    startYear: 907,
    endYear: 923,
    era: '隋唐五代',
    sortOrder: 101,
  },
  {
    id: 'tang-later',
    name: '后唐',
    aliases: null,
    startYear: 923,
    endYear: 936,
    era: '隋唐五代',
    sortOrder: 102,
  },
  {
    id: 'jin-later',
    name: '后晋',
    aliases: null,
    startYear: 936,
    endYear: 947,
    era: '隋唐五代',
    sortOrder: 103,
  },
  {
    id: 'zhou-later',
    name: '后周',
    aliases: null,
    startYear: 951,
    endYear: 960,
    era: '隋唐五代',
    sortOrder: 105,
  },

  // 宋辽金元
  {
    id: 'song',
    name: '宋',
    aliases: JSON.stringify(['宋朝']),
    startYear: 960,
    endYear: 1279,
    era: '宋元',
    sortOrder: 110,
  },
  {
    id: 'song-north',
    name: '北宋',
    aliases: null,
    startYear: 960,
    endYear: 1127,
    era: '宋元',
    sortOrder: 111,
  },
  {
    id: 'song-south',
    name: '南宋',
    aliases: null,
    startYear: 1127,
    endYear: 1279,
    era: '宋元',
    sortOrder: 112,
  },
  {
    id: 'liao',
    name: '辽',
    aliases: JSON.stringify(['辽国', '契丹']),
    startYear: 916,
    endYear: 1125,
    era: '宋元',
    sortOrder: 115,
  },
  {
    id: 'jin',
    name: '金',
    aliases: JSON.stringify(['金国', '金朝']),
    startYear: 1115,
    endYear: 1234,
    era: '宋元',
    sortOrder: 120,
  },
  {
    id: 'yuan',
    name: '元',
    aliases: JSON.stringify(['元朝', '蒙元']),
    startYear: 1271,
    endYear: 1368,
    era: '宋元',
    sortOrder: 130,
  },

  // 明清
  {
    id: 'ming',
    name: '明',
    aliases: JSON.stringify(['明朝']),
    startYear: 1368,
    endYear: 1644,
    era: '明清',
    sortOrder: 140,
  },
  {
    id: 'qing',
    name: '清',
    aliases: JSON.stringify(['清朝']),
    startYear: 1644,
    endYear: 1912,
    era: '明清',
    sortOrder: 150,
  },

  // 近现代
  {
    id: 'minguo',
    name: '民国',
    aliases: JSON.stringify(['中华民国']),
    startYear: 1912,
    endYear: 1949,
    era: '近现代',
    sortOrder: 160,
  },

  // 外国
  {
    id: 'silla',
    name: '新罗',
    aliases: null,
    startYear: -57,
    endYear: 935,
    era: '外国',
    sortOrder: 200,
    notes: '朝鲜半岛古国',
  },
  {
    id: 'goryeo',
    name: '高丽',
    aliases: JSON.stringify(['高丽国']),
    startYear: 918,
    endYear: 1392,
    era: '外国',
    sortOrder: 210,
    notes: '朝鲜半岛古国',
  },
  {
    id: 'japan',
    name: '日本',
    aliases: null,
    startYear: null,
    endYear: null,
    era: '外国',
    sortOrder: 220,
  },
  {
    id: 'hu',
    name: '胡',
    aliases: null,
    startYear: null,
    endYear: null,
    era: '外国',
    sortOrder: 230,
    notes: '泛指西域、北方民族',
  },
]
